'use client';

import React from 'react';
import Navbar from '../../components/Navbar';
import Footer from '../../components/Footer';

export default function SecurityPage() {
  return (
    <div className="antialiased min-h-screen flex flex-col bg-[#ebebeb]">
      
      {/* 1. HERO */}
      <section className="bg-black relative flex flex-col border-b border-black pt-8 pb-24">
        <div className="absolute top-0 left-0 w-full z-10">
          <Navbar />
        </div>
        
        <div className="pt-32 px-12 md:px-16 max-w-[1440px] mx-auto w-full text-white relative z-10 text-center">
            <div className="text-xs font-bold uppercase tracking-widest text-gray-500 mb-8 flex items-center justify-center gap-2 font-mono">
              <span className="w-4 h-[2px] bg-gray-500"></span> TRUST CENTER
            </div>
            <h1 className="text-5xl md:text-7xl font-medium tracking-tight mb-6">
              Security by design.
            </h1>
            <p className="text-gray-400 text-lg max-w-2xl mx-auto mb-12 leading-relaxed">
              We built our synthetic engine to meet the highest standards of data privacy. Generate identical statistical distributions without exposing a single row of real PII.
            </p>
            <div className="flex justify-center gap-4">
               <button className="bg-white text-black px-8 py-4 font-mono text-sm uppercase tracking-widest font-bold hover:bg-gray-200 transition">
                 View SOC2 Report
               </button>
               <button className="border border-white/20 text-white px-8 py-4 font-mono text-sm uppercase tracking-widest font-bold hover:bg-white/10 transition">
                 Contact Security
               </button>
            </div>
        </div>
      </section>

      {/* 2. COMPLIANCE BADGES */}
      <section className="bg-[#ebebeb] text-black border-b b-light">
         <div className="max-w-[1440px] mx-auto border-x b-light grid grid-cols-1 md:grid-cols-3">
            <div className="p-12 md:p-16 border-b md:border-b-0 border-r b-light flex flex-col items-center text-center">
               <div className="w-24 h-24 rounded-full border-4 border-black flex items-center justify-center mb-8">
                 <span className="font-bold text-2xl tracking-tight">SOC2</span>
               </div>
               <h3 className="text-2xl font-medium mb-4">SOC2 Type II</h3>
               <p className="text-gray-600 leading-relaxed text-sm">
                 Our infrastructure, access controls, and data practices are continuously audited by an independent third party to ensure strict security and availability.
               </p>
            </div>

            <div className="p-12 md:p-16 border-b md:border-b-0 border-r b-light flex flex-col items-center text-center">
               <div className="w-24 h-24 rounded-full border-4 border-black flex items-center justify-center mb-8">
                 <span className="font-bold text-2xl tracking-tight">HIPAA</span>
               </div>
               <h3 className="text-2xl font-medium mb-4">HIPAA Compliant</h3>
               <p className="text-gray-600 leading-relaxed text-sm">
                 We sign Business Associate Agreements (BAAs) with healthcare clients. Our differential privacy guarantees that PHI is never memorized or exposed.
               </p>
            </div>

            <div className="p-12 md:p-16 flex flex-col items-center text-center">
               <div className="w-24 h-24 rounded-full border-4 border-black flex items-center justify-center mb-8">
                 <span className="font-bold text-2xl tracking-tight">GDPR</span>
               </div>
               <h3 className="text-2xl font-medium mb-4">GDPR & CCPA</h3>
               <p className="text-gray-600 leading-relaxed text-sm">
                 Synthetic data generated by our engine contains no PII and is completely exempt from GDPR right-to-be-forgotten requests. We offer EU data localization.
               </p>
            </div>
         </div>
      </section>

      {/* 3. ARCHITECTURE DETAILS */}
      <section className="bg-[#ebebeb] text-black">
         <div className="max-w-[1440px] mx-auto border-x b-light">
            <div className="grid grid-cols-1 md:grid-cols-12">
               <div className="col-span-12 md:col-span-4 p-12 md:p-16 border-r b-light">
                  <h2 className="text-3xl font-medium mb-4">Zero Memorization Guarantee</h2>
                  <p className="text-gray-600 text-sm leading-relaxed">
                    Unlike naive LLMs or simple generative models, our core SDV engine utilizes mathematically proven differential privacy.
                  </p>
               </div>
               <div className="col-span-12 md:col-span-8 p-12 md:p-16 bg-white flex flex-col justify-center">
                  <div className="flex flex-col gap-8">
                     <div className="flex gap-6 items-start">
                        <div className="text-xs font-mono font-bold uppercase text-black pt-1">01</div>
                        <div>
                           <h4 className="text-xl font-medium mb-2">In-Memory Processing</h4>
                           <p className="text-gray-600 text-sm">Your original dataset is never stored on disk. It is held in ephemeral memory during the model fitting process and instantly destroyed upon completion.</p>
                        </div>
                     </div>
                     <div className="w-full h-px bg-black/10"></div>
                     <div className="flex gap-6 items-start">
                        <div className="text-xs font-mono font-bold uppercase text-black pt-1">02</div>
                        <div>
                           <h4 className="text-xl font-medium mb-2">Noise Injection (Epsilon)</h4>
                           <p className="text-gray-600 text-sm">We inject calibrated Laplacian noise during the aggregation phase. You have full control over the privacy budget (epsilon) to balance utility vs privacy.</p>
                        </div>
                     </div>
                     <div className="w-full h-px bg-black/10"></div>
                     <div className="flex gap-6 items-start">
                        <div className="text-xs font-mono font-bold uppercase text-black pt-1">03</div>
                        <div>
                           <h4 className="text-xl font-medium mb-2">Stateless Generation</h4>
                           <p className="text-gray-600 text-sm">The resulting artifact is a lightweight, stateless mathematical model of your data distribution. Generating new rows from this model requires zero network calls to your original DB.</p>
                        </div>
                     </div>
                  </div>
               </div>
            </div>
         </div>
      </section>

      <Footer />
    </div>
  );
}
